version: '3.7'
services:
  app:
    build:
      context: .
    container_name: react_front-${CONTAINER_PREFIX}
    restart: always
    volumes:
      - "./chat-ui/public:/app/public"
      - "./chat-ui/src:/app/src"
    command: npm start
    
    ports:
      - ${APP_PORT}:3000

    environment:
      - NODE_ENV=development